### ISSUE TITLE
run ./BING_linux   Invalidate class name

### ISSUE THREAD

**Issue by LinJM** [bittnt/Objectness#10]
when I run the ./BING_linux, I encounter the error:
jeremy@jeremy:~/jWork/Bing/BINGObjectness/Objectness/Src$ ./BING_linux 
Invalidate class name
 in /home/jeremy/jWork/Bing/BINGObjectness/Objectness/Src/DataSetVOC.cpp:123
OpenCV Error: Assertion failed (Invalidate class name
) in loadBox, file /home/jeremy/jWork/Bing/BINGObjectness/Objectness/Src/DataSetVOC.cpp, line 123
terminate called after throwing an instance of 'cv::Exception'
  what():  /home/jeremy/jWork/Bing/BINGObjectness/Objectness/Src/DataSetVOC.cpp:123: error: (-215) Invalidate class name
 in function loadBox

已放弃 (核心已转储)

**Comment by bittnt** [comment]
Hi, I think you d better check the class name file, if there is a \n in the end of that file, you might see this error. I hope this help you to resolve the problem.

**Comment by gautamMalu** [comment]
I was also stuck at the same error, I applied this patch https://github.com/westu/Objectness/commit/fa6eb8af6bd40e04a8fb56c96a860cdfe18e18c7

**Comment by bittnt** [comment]
@gautamMalu Thanks. @LinJM Please refer this patch. westu@fa6eb8a
