### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by June01** [bittnt/Objectness#12]
Hi, bittnx
I wondered how to merge the training data and testing data. I download the data from the official website, while the training and testing data is seperated. While in your code, I saw them was processed in a folder. 
trainSet = CmFile::loadStrList(wkDir + "ImageSets/Main/train.txt");
testSet = CmFile::loadStrList(wkDir + "ImageSets/Main/test.txt");
classNames = CmFile::loadStrList(wkDir + "ImageSets/Main/class.txt")
I even could not find class.txt in all the folders.
So when I do ./BING_linux , I met errors:
Dataset:`/home/june/projects/VOC2007' with 0 training and 0 testing
WinRecall.m Base = 2, W = 8, NSS = 2, perSz = 130
Invalidate CvMat data file /home/june/projects/VOC2007Results/ObjNessB2W8MAXBGR.xP
What should I do next? Thank you very much.

**Comment by RyanCV** [comment]
The train.txt, test.txt  and class.txt should be in the directory ~/ImageSets/Main/. If you didn't find them, make sure to download again from Mingming Cheng's website. 0 training and 0 testing means it didn't find the train.txt and test.txt. Another important thing is to check the format of .txt in linux. You can read this link:http://superuser.com/questions/294219/what-are-the-differences-between-linux-and-windows-txt-files-unicode-encoding.

**Comment by June01** [comment]
@RyanCV Hi, thanks to reply. When I works on opencv 3.0, I met problems in the issues before which cannot be solved. So, I change to opencv 2.4.9, while opencv_imgcodecs cannot be found. Could you tell me which subversion you use, such as 2.4.*?

**Comment by mtourne** [comment]
There is a bit of explanation missing on how to prep the vov2007 dataset for this. 

More info can be found in this github below, and as mentionned before it's important to fix the endlines of ImageSets/Main/class.txt to be Unix and not Windows

https://github.com/varun-nagaraja/BING-Objectness

**Comment by bittnt** [comment]
For dataset preparation, check:
http://kylezheng.org/objectproposal/
