### ISSUE TITLE
YAML files generated from xml2yml.m cannot be read by Opencv FilgStorage class  

### ISSUE THREAD

**Issue by seanXYZ** [bittnt/Objectness#4]
YAML files generated from xml2yml.m cannot be read by Opencv FilgStorage class  
after that , I noticed the comments in xml2yaml.m 
%% Convert the file type of opencv xml annotations to yaml thus it can be read by opencv 
% This functions relies on http://code.google.com/p/yamlmatlab/
% The results needs to be further refined to deal with indentation problem
what's  the meaning of  " needs to be further refined" ??

**Comment by bittnt** [comment]
Hi, @seanXYZ I am not sure which OpenCV version you are talking about. The code should works with the previous version 2.4.9. Alternatively, you could try the mexOpenCV https://github.com/kyamagu/mexopencv, it should help you getting things done with the latest OpenCV YAML interface.

**Comment by seanXYZ** [comment]
Hi, thank you for your message. I have already figured it out.And read and test all your code. 
The problem takes place because that the format of YAML can not be parsed on my machine.So I have tried different formats, this format below is working:
  %YAML:1.0

annotation:
  folder: VOC2007
  filename: "000001.jpg"
  source: {database: The VOC2007 Database, annotation: PASCAL VOC2007, image: flickr,
    flickrid: '341012865'}
  owner: {flickrid: Fried Camels, name: Jinky the Fruit Bat}
  size: {width: '353', height: '500', depth: '3'}
  segmented: '0'
  object:
    - bndbox: {xmin: '48', ymin: '240', xmax: '195', ymax: '371'}
      name: dog
      pose: Left
      truncated: '1'
      difficult: '0'
    - bndbox: {xmin: '8', ymin: '12', xmax: '352', ymax: '498'}
      name: person
      pose: Left
      truncated: '1'
      difficult: '0'

**Comment by ZhengYuxiao** [comment]
@seanXYZ  Hello, I want make own data set like VOC2007 Annotations, but the annotations is xml, I want generate yml,could you tell me how to generate the formats like follow
%YAML:1.0

annotation:
folder: VOC2007
filename: "000001.jpg"
source: {database: The VOC2007 Database, annotation: PASCAL VOC2007, image: flickr,
flickrid: '341012865'}
owner: {flickrid: Fried Camels, name: Jinky the Fruit Bat}
size: {width: '353', height: '500', depth: '3'}
segmented: '0'
object:
- bndbox: {xmin: '48', ymin: '240', xmax: '195', ymax: '371'}
name: dog
pose: Left
truncated: '1'
difficult: '0'
- bndbox: {xmin: '8', ymin: '12', xmax: '352', ymax: '498'}
name: person
pose: Left
truncated: '1'
difficult: '0'

**Comment by seanXYZ** [comment]
I think you can use a lot of APIs to edit your YAML file or XML file.  To the infomation of the object, you may write a program to select the box of it.
